### ISSUE TITLE
Definições de Casos de Uso e Tasks

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#30]
---

Vamos documentar aqui todos os Casos de Uso e as tasks para desenvolvimento que surgirem para cada UC.
Conforme forem sendo adicionados novos comentários, irei atualizando a lista abaixo:

### _Obs: Apenas casos de uso numerados têm sua prioridade estabelecida. Os demais precisam ser discutidos e numerados._

---

## **CASOS DE USO OBRIGATÓRIOS**

- [ ]  UC8 - Como funcionário, quero visualizar a lista de produtos disponíveis por categoria, selecionar um produto e gerar um pedido ([conforme a RN05](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn05));
- [ ]  UC9 - Como funcionário, quero fechar uma comanda de um cliente ([conforme a RN01](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn01), [RN02](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn02));
- [ ]  UC10 - Como funcionário, quero reservar uma mesa ([conforme a RN03](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn03));
- [ ]  UC11 - Como funcionário, quero abrir comanda por cliente e adicionar a comanda a uma mesa (conforme a regra de cliente cadastrado e [RN04](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn04));
- [ ]  UC12 - Como funcionário, quero verificar as mesas disponíveis e suas capacidades (conforme a regra de verificação de quantidade máxima de pessoas);
- [ ]  UC13 - Como caixa, quero receber uma comanda, alterar seu status para paga e remover ela da mesa ([conforme a RN08](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn08));

## **CASOS DE USO OPCIONAIS**

- [ ]  UCx - Como garçom, quero listar os clientes existentes numa mesa ([conforme a RN07](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn07));
- [ ]  UCx - Como gerente, quero verificar as comandas de uma mesa a partir de um status (EM ABERTO/FECHADA/PAGA) ([conforme a RN08](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn08));

## **TASKS PARA DESENVOLVIMENTO**

- [ ] UC7 - Task: ProdutoRepository adicionarPedido(Produto produto)
- [ ] UC8 - Task: ProdutoService visualisarProdutosPorCategoria() + PedidoService adicionarPedidoComanda(Pedido pedido, Comanda comanda);
- [ ] UC9 - Task: ComandaService fecharComanda(Comanda comanda);
- [ ] UC10 - Task: MesaService reservarMesa(Mesa mesa);
- [ ] UC11 - Task: ComandaService abrirComandaPorClienteEAdicionarMesa(Cliente cliente, Mesa mesa);
- [ ] UC12 - Task: MesaService verificarMesasDisponiveisECapacidades();
- [ ] UC13 - Task: CaixaService receberComandaAlterarStatusParaPagaERemoverDaMesa(Comanda comanda);

**Comment by regis-amaral** [comment]
**CASOS DE USO:**

- [ ] UC - Como funcionário quero verificar as mesas disponiveis e suas capacidades
- [ ] UC - Como funcionário quero reservar uma mesa
- [ ] UC - Como funcionário quero abrir comanda por cliente e adicionar a uma mesa
- [ ] UC - Como funcionário quero fechar uma comanda de um cliente
- [ ] UC - Como caixa quero receber uma comanda, alterar seu status para paga e remover ela da mesa

**Comment by tiagospeckart** [comment]
Tem o notion do Márcio que podemos nos basear também
 https://marciomichelluzzi.notion.site/Projeto-Final-623b2a40c7db4d7caedc1afd618274ad

**Comment by regis-amaral** [comment]
Implementar lógica para criação de mesa e seus métodos

**Comment by tiagospeckart** [comment]
Tenho algumas propostas para a gente evoluir essa issue. 

- [ ] Edição do post original para adicionar as UCs obrigatórias, conforme descrito no [Notion pelo professor Márcio](https://marciomichelluzzi.notion.site/Projeto-Final-623b2a40c7db4d7caedc1afd618274ad) e baseado nas Regras de Negócio. A numeração já atribuída indica a obrigatoriedade desses casos de uso.
- [x] Criação de uma página própria para as Regras de Negócio na nossa [Wiki](https://github.com/RavinProject/ProjetoRavin/wiki).
- [x] Caso todos estejam de acordo com as UCs, podemos também adicioná-las em uma nova página da Wiki (Já me adiantei e criei a página, mas qualquer coisa posso editar)
- [ ] Revisão das tasks (como foram geradas por ChatGPT, certamente precisam ser revisadas)

---

Vamos documentar aqui todos os Casos de Uso e as tasks para desenvolvimento que surgirem para cada UC.
Conforme forem sendo adicionados novos comentários, irei atualizando a lista abaixo:

_Obs: Apenas casos de uso numerados têm sua prioridade estabelecida. Os demais precisam ser discutidos e numerados._

## **CASOS DE USO OBRIGATÓRIOS**

- [ ] UC8 - Como funcionário, quero visualizar a lista de produtos disponíveis por categoria, selecionar um produto e gerar um pedido ([conforme a RN05](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn05));
- [ ] UC9 - Como funcionário, quero fechar uma comanda de um cliente ([conforme a RN01](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn01), [RN02](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn02));
- [ ] UC10 - Como funcionário, quero reservar uma mesa ([conforme a RN03](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn03));
- [ ] UC11 - Como funcionário, quero abrir comanda por cliente e adicionar a comanda a uma mesa (conforme a regra de cliente cadastrado e [RN04](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn04));
- [ ] UC12 - Como funcionário, quero verificar as mesas disponíveis e suas capacidades (conforme a regra de verificação de quantidade máxima de pessoas);
- [ ] UC13 - Como caixa, quero receber uma comanda, alterar seu `status` para paga e remover ela da mesa ([conforme a RN08](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn08));

## **CASOS DE USO OPCIONAIS**

- [ ] UCx - Como garçom, quero listar os clientes existentes numa mesa ([conforme a RN07](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn07));
- [ ] UCx - Como gerente, quero verificar as comandas de uma mesa a partir de um `status` (EM ABERTO/FECHADA/PAGA) ([conforme a RN08](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn08));

## **TASKS PARA DESENVOLVIMENTO**

- UC8 - Task: ProdutoService visualisarProdutosPorCategoria() + PedidoService adicionarPedidoComanda(Pedido pedido, Comanda comanda);
- UC9 - Task: ComandaService fecharComanda(Comanda comanda);
- UC10 - Task: MesaService reservarMesa(Mesa mesa);
- UC11 - Task: ComandaService abrirComandaPorClienteEAdicionarMesa(Cliente cliente, Mesa mesa);
- UC12 - Task: MesaService verificarMesasDisponiveisECapacidades();
- UC13 - Task: CaixaService receberComandaAlterarStatusParaPagaERemoverDaMesa(Comanda comanda);

**Comment by regis-amaral** [comment]
@tiagospeckart Atualizado!
