### ISSUE TITLE
Criar Serviço de Desconto + PagarComanda

### ISSUE THREAD

**Issue by tiagospeckart** [regis-amaral/ProjetoRavin#33]
Referente [RN01](https://github.com/RavinProject/ProjetoRavin/wiki/Regras-de-Negocio#rn01)

## Tasks

- [x] Criar interface de Desconto
- [x] Criar Classe de Estratégias de Desconto
- [x] Refatorar Serviço Comanda
- [x] Alterar Controlador Comanda para depender de Serviço

## Opcional

- [ ] Fazer um teste de unidade para o Serviço de PagarComanda, mas para isso precisamos considerar opções de usar dependências externas. Aberta a questão

**Comment by tiagospeckart** [comment]
Opcional:
- [x] Fazer um teste de unidade para o Serviço de PagarComanda, mas para isso precisamos considerar opções de usar dependências externas. Aberta a questão
- #38
