### ISSUE TITLE
Implementação das Classes e Interfaces de Serviços

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#37]
Implementação da camada de serviços.

Alterações:
- [x] Cliente: Controler, Service, Repository; Issue #40 
- [x] Estoque: Controler, Service, Repository; #41 
- [x] Produto: Controler, Service, Repository; #43
- [x] Funcionario: Controler, Service, Repository; #42

...

![Image](https://github.com/RavinProject/ProjetoRavin/assets/118540708/3defb77b-64e7-4c4a-b8ad-bfe27e252cdc)

**Comment by regis-amaral** [comment]
testando
